/**
 * @claw/core — Shared types used across all packages.
 */

/** A Crawfish-managed application. */
export interface CrawfishApp {
  id: string;
  name: string;
  accountId: string;
  platform: 'web' | 'ios' | 'android' | 'backend' | 'other';
  createdAt: Date;
  config?: CrawfishAppConfig;
}

export interface CrawfishAppConfig {
  repoProvider?: 'github' | 'gitlab' | 'bitbucket';
  repoOwner?: string;
  repoName?: string;
  baseBranch?: string;
  flagProvider?: 'crawfish' | 'launchdarkly' | 'statsig' | 'optimizely' | 'custom';
  autoFix?: boolean;
  autoExperiment?: boolean;
}

/** Account / organization. */
export interface CrawfishAccount {
  id: string;
  name: string;
  plan: CrawfishPlan;
  email: string;
  createdAt: Date;
}

export type CrawfishPlan = 'scout' | 'monitor' | 'improve' | 'autopilot' | 'enterprise';

/** Fix PR generated by Crawfish. */
export interface CrawfishFix {
  id: string;
  appId: string;
  issueId: string;
  prUrl: string;
  status: 'draft' | 'open' | 'merged' | 'closed' | 'reverted';
  experimentId?: string;
  createdAt: Date;
}

/** Experiment definition. */
export interface CrawfishExperiment {
  id: string;
  appId: string;
  fixId?: string;
  flagKey: string;
  variants: ExperimentVariant[];
  status: 'draft' | 'running' | 'paused' | 'completed' | 'rolled_back';
  startedAt?: Date;
  endedAt?: Date;
  results?: ExperimentResults;
}

export interface ExperimentVariant {
  key: string;
  name: string;
  weight: number; // 0-100
}

export interface ExperimentResults {
  sampleSize: number;
  winner?: string;
  confidence: number;
  metrics: Record<string, { control: number; treatment: number; lift: number }>;
}
