// ============================================================================
// Configuration Loader — agent-identity.yaml
// ============================================================================

import { readFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import type { AgentIdentity } from './types.js';

/** Parse YAML without a dependency — handles the simple subset we need */
function parseSimpleYaml(text: string): any {
  // For production, use the 'yaml' package. This is a minimal fallback.
  // We'll try dynamic import of 'yaml' first.
  throw new Error('YAML parsing requires the yaml package. Install with: npm install yaml');
}

let yamlParse: ((text: string) => any) | null = null;

async function getYamlParser(): Promise<(text: string) => any> {
  if (yamlParse) return yamlParse;
  try {
    const yaml = await import('yaml');
    yamlParse = yaml.parse || yaml.default?.parse;
    if (yamlParse) return yamlParse;
  } catch {}
  // Fallback: try JSON (config could be JSON too)
  yamlParse = JSON.parse;
  return yamlParse;
}

export interface ConfigOptions {
  /** Path to config file. Default: ./agent-identity.yaml */
  configPath?: string;
  /** Override values from env vars */
  envOverrides?: boolean;
}

export async function loadConfig(opts?: ConfigOptions): Promise<AgentIdentity> {
  const configPath = resolve(opts?.configPath || 'agent-identity.yaml');

  let raw: string;
  try {
    raw = await readFile(configPath, 'utf8');
  } catch (err: any) {
    if (err.code === 'ENOENT') {
      throw new Error(
        `Config file not found: ${configPath}\n` +
        `Run 'crawfish-identity init' to create one.`
      );
    }
    throw err;
  }

  const parse = await getYamlParser();
  const config = parse(raw) as AgentIdentity;

  // Validate required fields
  if (!config.agent?.name) throw new Error('Config missing: agent.name');
  if (!config.agent?.owner) throw new Error('Config missing: agent.owner');
  if (!config.identity?.email?.address) throw new Error('Config missing: identity.email.address');

  // Apply env overrides
  if (opts?.envOverrides !== false) {
    if (process.env.CRAWFISH_AGENT_NAME) config.agent.name = process.env.CRAWFISH_AGENT_NAME;
    if (process.env.CRAWFISH_OWNER) config.agent.owner = process.env.CRAWFISH_OWNER;
  }

  // Resolve paths
  const home = process.env.HOME || '';
  if (config.identity?.authenticator?.vault_path) {
    config.identity.authenticator.vault_path =
      config.identity.authenticator.vault_path.replace('~', home);
  }
  if (config.audit?.path) {
    config.audit.path = config.audit.path.replace('~', home);
  }

  return config;
}

/** Generate a default config file */
export function generateDefaultConfig(opts: {
  agentName: string;
  owner: string;
  domain?: string;
}): string {
  return `# Crawfish Agent Identity Configuration
# Generated by crawfish-identity init

agent:
  name: ${opts.agentName}
  owner: ${opts.owner}

identity:
  email:
    provider: cloudflare
    domain: ${opts.domain || 'example.com'}
    address: ${opts.agentName}@${opts.domain || 'example.com'}
  phone:
    provider: twilio
    enabled: false
  authenticator:
    type: totp
    vault_path: ~/.crawfish/vault.enc

services:
  # Add services with: crawfish-identity grant <service>
  # github:
  #   method: oauth
  #   scopes: [repo, read:org]
  #   org: your-org

audit:
  path: ~/.crawfish/agent-audit.jsonl
  retention_days: 90
`;
}
