/**
 * @fileoverview TypeScript interfaces for memory schema
 * @description Defines data structures for user memory, context scoping, and daily logs
 */

import * as admin from 'firebase-admin';

/**
 * Available request types for context scoping
 */
export type RequestType = 
  | 'meal-scan' 
  | 'meal-log' 
  | 'coach-chat' 
  | 'workout' 
  | 'weekly-review';

/**
 * Memory tiers based on user subscription
 */
export type MemoryTier = 'basic' | 'enhanced' | 'unlimited';

/**
 * Meal entry from photo scan or manual input
 */
export interface MealEntry {
  /** Unique identifier for the meal */
  id: string;
  /** Timestamp when meal was logged */
  timestamp: admin.firestore.Timestamp;
  /** Meal type (breakfast, lunch, dinner, snack) */
  type: 'breakfast' | 'lunch' | 'dinner' | 'snack';
  /** Food items in the meal */
  foods: FoodItem[];
  /** Photo URL if scanned from image */
  photoUrl?: string;
  /** AI-generated description of the meal */
  description: string;
  /** User's notes about the meal */
  notes?: string;
  /** Total estimated calories */
  totalCalories: number;
  /** Macro breakdown */
  macros: MacroNutrients;
  /** Confidence score of nutritional analysis (0-1) */
  confidence: number;
}

/**
 * Individual food item within a meal
 */
export interface FoodItem {
  /** Food name */
  name: string;
  /** Portion size */
  portion: string;
  /** Estimated calories */
  calories: number;
  /** Macronutrients */
  macros: MacroNutrients;
  /** Food category (protein, vegetable, grain, etc.) */
  category: string;
}

/**
 * Macronutrient breakdown
 */
export interface MacroNutrients {
  /** Protein in grams */
  protein: number;
  /** Carbohydrates in grams */
  carbs: number;
  /** Fat in grams */
  fat: number;
  /** Fiber in grams */
  fiber: number;
  /** Sugar in grams */
  sugar: number;
  /** Sodium in mg */
  sodium: number;
}

/**
 * Workout session entry
 */
export interface WorkoutEntry {
  /** Unique identifier for the workout */
  id: string;
  /** Timestamp when workout was logged */
  timestamp: admin.firestore.Timestamp;
  /** Type of workout */
  type: 'strength' | 'cardio' | 'flexibility' | 'sports' | 'other';
  /** Workout name/title */
  name: string;
  /** Duration in minutes */
  duration: number;
  /** Exercises performed */
  exercises: Exercise[];
  /** User's notes about the workout */
  notes?: string;
  /** Perceived exertion (1-10) */
  exertion?: number;
  /** Estimated calories burned */
  caloriesBurned?: number;
}

/**
 * Individual exercise within a workout
 */
export interface Exercise {
  /** Exercise name */
  name: string;
  /** Number of sets */
  sets?: number;
  /** Reps per set */
  reps?: number;
  /** Weight used (in kg) */
  weight?: number;
  /** Duration for time-based exercises (in seconds) */
  duration?: number;
  /** Distance for cardio exercises (in meters) */
  distance?: number;
  /** Exercise notes */
  notes?: string;
}

/**
 * Daily log containing all activities for a specific date
 */
export interface DailyLog {
  /** Date in YYYY-MM-DD format */
  date: string;
  /** All meals logged for this day */
  meals: MealEntry[];
  /** All workouts logged for this day */
  workouts: WorkoutEntry[];
  /** User's daily notes and reflections */
  notes: string[];
  /** Mood rating (1-10) */
  mood: number | null;
  /** Weight measurement in kg */
  weight: number | null;
  /** Sleep hours */
  sleep: number | null;
  /** Water intake in liters */
  water: number | null;
  /** Daily goals completion */
  goalProgress: {
    calories: { target: number; actual: number } | null;
    protein: { target: number; actual: number } | null;
    steps: { target: number; actual: number } | null;
  };
  /** Document creation timestamp */
  createdAt: admin.firestore.Timestamp;
  /** Last update timestamp */
  updatedAt: admin.firestore.Timestamp;
}

/**
 * Weekly memory summary generated by AI
 */
export interface WeeklyMemorySummary {
  /** Week start date (YYYY-MM-DD) */
  weekStart: string;
  /** Week end date (YYYY-MM-DD) */
  weekEnd: string;
  /** AI-generated summary of the week */
  summary: string;
  /** Key patterns and insights */
  insights: string[];
  /** Progress towards goals */
  goalProgress: string;
  /** Recommendations for next week */
  recommendations: string[];
  /** Generated timestamp */
  generatedAt: admin.firestore.Timestamp;
}

/**
 * Monthly memory summary for long-term tracking
 */
export interface MonthlyMemorySummary {
  /** Month in YYYY-MM format */
  month: string;
  /** AI-generated monthly summary */
  summary: string;
  /** Major achievements and milestones */
  achievements: string[];
  /** Challenges and areas for improvement */
  challenges: string[];
  /** Long-term trend analysis */
  trends: {
    weight?: string;
    fitness?: string;
    nutrition?: string;
    mood?: string;
  };
  /** Goals for next month */
  nextMonthGoals: string[];
  /** Generated timestamp */
  generatedAt: admin.firestore.Timestamp;
}

/**
 * User context data for AI interactions
 */
export interface UserContext {
  /** User's current goals and preferences */
  goals: string[];
  /** Dietary restrictions and preferences */
  dietaryRestrictions: string[];
  /** Workout preferences */
  workoutPreferences: string[];
  /** Recent daily logs (last 7-30 days) */
  recentLogs: DailyLog[];
  /** Weekly summaries */
  weeklySummaries: WeeklyMemorySummary[];
  /** Monthly summaries */
  monthlySummaries: MonthlyMemorySummary[];
  /** Current weight and measurements */
  currentStats: {
    weight: number | null;
    bodyFat: number | null;
    muscleMass: number | null;
  };
  /** Progress tracking */
  progress: {
    weightChange: number; // kg change over last 30 days
    strengthProgress: string;
    consistencyScore: number; // 0-100
  };
}

/**
 * Scoped context data returned based on request type
 */
export interface ScopedContext {
  /** Request type that determined the scope */
  requestType: RequestType;
  /** Basic user info always included */
  user: {
    goals: string[];
    dietaryRestrictions: string[];
    preferences: any;
  };
  /** Recent data relevant to request type */
  recentData: {
    meals?: MealEntry[];
    workouts?: WorkoutEntry[];
    logs?: DailyLog[];
  };
  /** AI summaries relevant to request type */
  summaries?: {
    weekly?: WeeklyMemorySummary[];
    monthly?: MonthlyMemorySummary[];
  };
  /** Context generation timestamp */
  generatedAt: admin.firestore.Timestamp;
}

/**
 * Memory refresh job configuration
 */
export interface MemoryRefreshConfig {
  /** How often to run weekly summaries (in days) */
  weeklyRefreshInterval: number;
  /** How often to run monthly summaries (in days) */
  monthlyRefreshInterval: number;
  /** Maximum days of daily logs to keep */
  maxDailyLogRetention: number;
  /** Memory tier affecting retention and detail level */
  memoryTier: MemoryTier;
}