// Comprehensive MCC (Merchant Category Code) lookup table
// Sources: ISO 18245, Visa/Mastercard merchant category codes

export interface MCCEntry {
  category: string;
  description: string;
  suggestedBudgetCategory: string;
}

export const MCC_CODES: Record<string, MCCEntry> = {
  // ─── Agricultural Services ───────────────────────────────────────────
  '0742': { category: 'Veterinary Services', description: 'Pet Care', suggestedBudgetCategory: 'Pet' },
  '0763': { category: 'Agricultural Cooperatives', description: 'Agriculture', suggestedBudgetCategory: 'Shopping' },
  '0780': { category: 'Landscaping/Horticultural Services', description: 'Home', suggestedBudgetCategory: 'Home Improvement' },

  // ─── Airlines ────────────────────────────────────────────────────────
  '3000': { category: 'United Airlines', description: 'Travel', suggestedBudgetCategory: 'Travel' },
  '3001': { category: 'American Airlines', description: 'Travel', suggestedBudgetCategory: 'Travel' },
  '3002': { category: 'Pan American', description: 'Travel', suggestedBudgetCategory: 'Travel' },
  '3003': { category: 'Eurofly', description: 'Travel', suggestedBudgetCategory: 'Travel' },
  '3004': { category: 'Dragon Air', description: 'Travel', suggestedBudgetCategory: 'Travel' },
  '3005': { category: 'British Airways', description: 'Travel', suggestedBudgetCategory: 'Travel' },
  '3006': { category: 'Japan Airlines', description: 'Travel', suggestedBudgetCategory: 'Travel' },
  '3007': { category: 'Air France', description: 'Travel', suggestedBudgetCategory: 'Travel' },
  '3008': { category: 'Lufthansa', description: 'Travel', suggestedBudgetCategory: 'Travel' },
  '3009': { category: 'Air Canada', description: 'Travel', suggestedBudgetCategory: 'Travel' },
  '3010': { category: 'Royal Dutch Airlines (KLM)', description: 'Travel', suggestedBudgetCategory: 'Travel' },
  '3011': { category: 'Aeroflot', description: 'Travel', suggestedBudgetCategory: 'Travel' },
  '3012': { category: 'Qantas', description: 'Travel', suggestedBudgetCategory: 'Travel' },
  '3013': { category: 'Alitalia', description: 'Travel', suggestedBudgetCategory: 'Travel' },
  '3014': { category: 'Saudi Arabian Airlines', description: 'Travel', suggestedBudgetCategory: 'Travel' },
  '3015': { category: 'Swiss International Air Lines', description: 'Travel', suggestedBudgetCategory: 'Travel' },
  '3016': { category: 'SAS (Scandinavian)', description: 'Travel', suggestedBudgetCategory: 'Travel' },
  '3017': { category: 'South African Airways', description: 'Travel', suggestedBudgetCategory: 'Travel' },
  '3018': { category: 'Varig', description: 'Travel', suggestedBudgetCategory: 'Travel' },
  '3020': { category: 'Air India', description: 'Travel', suggestedBudgetCategory: 'Travel' },
  '3021': { category: 'Air Algerie', description: 'Travel', suggestedBudgetCategory: 'Travel' },
  '3023': { category: 'TAP (Portugal)', description: 'Travel', suggestedBudgetCategory: 'Travel' },
  '3026': { category: 'Ryanair', description: 'Travel', suggestedBudgetCategory: 'Travel' },
  '3031': { category: 'Delta Air Lines', description: 'Travel', suggestedBudgetCategory: 'Travel' },
  '3032': { category: 'El Al', description: 'Travel', suggestedBudgetCategory: 'Travel' },
  '3033': { category: 'Finnair', description: 'Travel', suggestedBudgetCategory: 'Travel' },
  '3035': { category: 'Singapore Airlines', description: 'Travel', suggestedBudgetCategory: 'Travel' },
  '3036': { category: 'Emirates', description: 'Travel', suggestedBudgetCategory: 'Travel' },
  '3038': { category: 'Turkish Airlines', description: 'Travel', suggestedBudgetCategory: 'Travel' },
  '3039': { category: 'Icelandair', description: 'Travel', suggestedBudgetCategory: 'Travel' },
  '3044': { category: 'Air Lanka', description: 'Travel', suggestedBudgetCategory: 'Travel' },
  '3045': { category: 'Cathay Pacific', description: 'Travel', suggestedBudgetCategory: 'Travel' },
  '3048': { category: 'China Airlines', description: 'Travel', suggestedBudgetCategory: 'Travel' },
  '3058': { category: 'Copa Airlines', description: 'Travel', suggestedBudgetCategory: 'Travel' },
  '3060': { category: 'Northwest Airlines', description: 'Travel', suggestedBudgetCategory: 'Travel' },
  '3061': { category: 'Austrian Airlines', description: 'Travel', suggestedBudgetCategory: 'Travel' },
  '3065': { category: 'LOT Polish Airlines', description: 'Travel', suggestedBudgetCategory: 'Travel' },
  '3066': { category: 'JetBlue', description: 'Travel', suggestedBudgetCategory: 'Travel' },
  '3068': { category: 'Air Italy', description: 'Travel', suggestedBudgetCategory: 'Travel' },
  '3071': { category: 'Korean Air', description: 'Travel', suggestedBudgetCategory: 'Travel' },
  '3075': { category: 'Alaska Airlines', description: 'Travel', suggestedBudgetCategory: 'Travel' },
  '3076': { category: 'Hawaiian Airlines', description: 'Travel', suggestedBudgetCategory: 'Travel' },
  '3077': { category: 'Iberia Airlines', description: 'Travel', suggestedBudgetCategory: 'Travel' },
  '3082': { category: 'Southwest Airlines', description: 'Travel', suggestedBudgetCategory: 'Travel' },
  '3083': { category: 'Sun Country Airlines', description: 'Travel', suggestedBudgetCategory: 'Travel' },
  '3085': { category: 'EVA Airways', description: 'Travel', suggestedBudgetCategory: 'Travel' },
  '3087': { category: 'Ethiopian Airlines', description: 'Travel', suggestedBudgetCategory: 'Travel' },
  '3090': { category: 'EasyJet', description: 'Travel', suggestedBudgetCategory: 'Travel' },
  '3096': { category: 'Spirit Airlines', description: 'Travel', suggestedBudgetCategory: 'Travel' },
  '3097': { category: 'Frontier Airlines', description: 'Travel', suggestedBudgetCategory: 'Travel' },
  '3099': { category: 'Allegiant Air', description: 'Travel', suggestedBudgetCategory: 'Travel' },
  '3100': { category: 'Cathay Pacific', description: 'Travel', suggestedBudgetCategory: 'Travel' },
  '3117': { category: 'Avianca', description: 'Travel', suggestedBudgetCategory: 'Travel' },
  '3137': { category: 'JetBlue', description: 'Travel', suggestedBudgetCategory: 'Travel' },
  '3144': { category: 'Qatar Airways', description: 'Travel', suggestedBudgetCategory: 'Travel' },
  '3148': { category: 'Air New Zealand', description: 'Travel', suggestedBudgetCategory: 'Travel' },
  '3159': { category: 'All Nippon Airways', description: 'Travel', suggestedBudgetCategory: 'Travel' },
  '3174': { category: 'Jet Airways', description: 'Travel', suggestedBudgetCategory: 'Travel' },
  '3175': { category: 'WestJet', description: 'Travel', suggestedBudgetCategory: 'Travel' },
  '3196': { category: 'Virgin America', description: 'Travel', suggestedBudgetCategory: 'Travel' },
  '3211': { category: 'Norwegian Air', description: 'Travel', suggestedBudgetCategory: 'Travel' },
  '3212': { category: 'TAM Airlines', description: 'Travel', suggestedBudgetCategory: 'Travel' },
  '3236': { category: 'Volaris', description: 'Travel', suggestedBudgetCategory: 'Travel' },
  '3245': { category: 'Wizz Air', description: 'Travel', suggestedBudgetCategory: 'Travel' },
  '3261': { category: 'Air China', description: 'Travel', suggestedBudgetCategory: 'Travel' },
  '3292': { category: 'AirTran', description: 'Travel', suggestedBudgetCategory: 'Travel' },
  '3351': { category: 'Hertz', description: 'Car Rental', suggestedBudgetCategory: 'Travel' },
  '3352': { category: 'Avis', description: 'Car Rental', suggestedBudgetCategory: 'Travel' },
  '3353': { category: 'National Car Rental', description: 'Car Rental', suggestedBudgetCategory: 'Travel' },
  '3354': { category: 'Budget Rent-A-Car', description: 'Car Rental', suggestedBudgetCategory: 'Travel' },
  '3355': { category: 'Payless Car Rental', description: 'Car Rental', suggestedBudgetCategory: 'Travel' },
  '3357': { category: 'Enterprise Rent-A-Car', description: 'Car Rental', suggestedBudgetCategory: 'Travel' },
  '3359': { category: 'Dollar Rent-A-Car', description: 'Car Rental', suggestedBudgetCategory: 'Travel' },
  '3360': { category: 'Thrifty Car Rental', description: 'Car Rental', suggestedBudgetCategory: 'Travel' },
  '3361': { category: 'Advantage Car Rental', description: 'Car Rental', suggestedBudgetCategory: 'Travel' },
  '3362': { category: 'Alamo Rent-A-Car', description: 'Car Rental', suggestedBudgetCategory: 'Travel' },
  '3366': { category: 'Europcar', description: 'Car Rental', suggestedBudgetCategory: 'Travel' },
  '3368': { category: 'Sixt', description: 'Car Rental', suggestedBudgetCategory: 'Travel' },
  '3370': { category: 'Ace Rent-A-Car', description: 'Car Rental', suggestedBudgetCategory: 'Travel' },
  '3385': { category: 'Zipcar', description: 'Car Rental', suggestedBudgetCategory: 'Travel' },
  '3389': { category: 'Turo', description: 'Car Rental', suggestedBudgetCategory: 'Travel' },

  // ─── Hotels/Lodging ──────────────────────────────────────────────────
  '3501': { category: 'Hilton Hotels', description: 'Lodging', suggestedBudgetCategory: 'Travel' },
  '3502': { category: 'Sheraton', description: 'Lodging', suggestedBudgetCategory: 'Travel' },
  '3503': { category: 'Best Western', description: 'Lodging', suggestedBudgetCategory: 'Travel' },
  '3504': { category: 'Holiday Inn', description: 'Lodging', suggestedBudgetCategory: 'Travel' },
  '3505': { category: 'Marriott', description: 'Lodging', suggestedBudgetCategory: 'Travel' },
  '3506': { category: 'Hyatt', description: 'Lodging', suggestedBudgetCategory: 'Travel' },
  '3507': { category: 'Days Inn', description: 'Lodging', suggestedBudgetCategory: 'Travel' },
  '3508': { category: 'Ramada', description: 'Lodging', suggestedBudgetCategory: 'Travel' },
  '3509': { category: 'Howard Johnson', description: 'Lodging', suggestedBudgetCategory: 'Travel' },
  '3510': { category: 'Red Roof Inn', description: 'Lodging', suggestedBudgetCategory: 'Travel' },
  '3511': { category: 'Westin', description: 'Lodging', suggestedBudgetCategory: 'Travel' },
  '3512': { category: 'La Quinta', description: 'Lodging', suggestedBudgetCategory: 'Travel' },
  '3515': { category: 'Fairmont', description: 'Lodging', suggestedBudgetCategory: 'Travel' },
  '3516': { category: 'Omni Hotels', description: 'Lodging', suggestedBudgetCategory: 'Travel' },
  '3517': { category: 'DoubleTree', description: 'Lodging', suggestedBudgetCategory: 'Travel' },
  '3518': { category: 'Four Seasons', description: 'Lodging', suggestedBudgetCategory: 'Travel' },
  '3519': { category: 'Wyndham', description: 'Lodging', suggestedBudgetCategory: 'Travel' },
  '3520': { category: 'Motel 6', description: 'Lodging', suggestedBudgetCategory: 'Travel' },
  '3527': { category: 'Embassy Suites', description: 'Lodging', suggestedBudgetCategory: 'Travel' },
  '3528': { category: 'Comfort Inn', description: 'Lodging', suggestedBudgetCategory: 'Travel' },
  '3530': { category: 'Courtyard by Marriott', description: 'Lodging', suggestedBudgetCategory: 'Travel' },
  '3531': { category: 'Hampton Inn', description: 'Lodging', suggestedBudgetCategory: 'Travel' },
  '3535': { category: 'W Hotels', description: 'Lodging', suggestedBudgetCategory: 'Travel' },
  '3542': { category: 'Club Med', description: 'Lodging', suggestedBudgetCategory: 'Travel' },
  '3546': { category: 'Super 8', description: 'Lodging', suggestedBudgetCategory: 'Travel' },
  '3550': { category: 'Extended Stay America', description: 'Lodging', suggestedBudgetCategory: 'Travel' },
  '3558': { category: 'Residence Inn', description: 'Lodging', suggestedBudgetCategory: 'Travel' },
  '3562': { category: 'SpringHill Suites', description: 'Lodging', suggestedBudgetCategory: 'Travel' },
  '3565': { category: 'TownePlace Suites', description: 'Lodging', suggestedBudgetCategory: 'Travel' },
  '3573': { category: 'Airbnb', description: 'Lodging', suggestedBudgetCategory: 'Travel' },
  '3589': { category: 'VRBO', description: 'Lodging', suggestedBudgetCategory: 'Travel' },
  '7011': { category: 'Hotels, Motels, Resorts', description: 'Lodging', suggestedBudgetCategory: 'Travel' },

  // ─── Transportation ──────────────────────────────────────────────────
  '4011': { category: 'Railroads', description: 'Transportation', suggestedBudgetCategory: 'Transportation' },
  '4111': { category: 'Local/Suburban Commuter Passenger Transportation', description: 'Transportation', suggestedBudgetCategory: 'Transportation' },
  '4112': { category: 'Passenger Railways', description: 'Transportation', suggestedBudgetCategory: 'Transportation' },
  '4119': { category: 'Ambulance Services', description: 'Healthcare', suggestedBudgetCategory: 'Healthcare' },
  '4121': { category: 'Taxicabs/Rideshare', description: 'Transportation', suggestedBudgetCategory: 'Transportation' },
  '4131': { category: 'Bus Lines', description: 'Transportation', suggestedBudgetCategory: 'Transportation' },
  '4214': { category: 'Motor Freight, Moving & Storage', description: 'Transportation', suggestedBudgetCategory: 'Shopping' },
  '4215': { category: 'Courier Services', description: 'Shipping', suggestedBudgetCategory: 'Shopping' },
  '4225': { category: 'Public Warehousing, Storage', description: 'Storage', suggestedBudgetCategory: 'Shopping' },
  '4411': { category: 'Cruise Lines', description: 'Travel', suggestedBudgetCategory: 'Travel' },
  '4457': { category: 'Boat Rentals/Leases', description: 'Travel', suggestedBudgetCategory: 'Travel' },
  '4468': { category: 'Marinas/Marine Service', description: 'Travel', suggestedBudgetCategory: 'Travel' },
  '4511': { category: 'Airlines/Air Carriers', description: 'Travel', suggestedBudgetCategory: 'Travel' },
  '4582': { category: 'Airports/Airport Terminals', description: 'Travel', suggestedBudgetCategory: 'Travel' },
  '4722': { category: 'Travel Agencies/Tour Operators', description: 'Travel', suggestedBudgetCategory: 'Travel' },
  '4784': { category: 'Tolls/Bridge Fees', description: 'Transportation', suggestedBudgetCategory: 'Transportation' },
  '4789': { category: 'Transportation Services', description: 'Transportation', suggestedBudgetCategory: 'Transportation' },
  '4812': { category: 'Telecommunication Equipment', description: 'Utilities', suggestedBudgetCategory: 'Utilities' },
  '4814': { category: 'Telephone Services', description: 'Utilities', suggestedBudgetCategory: 'Utilities' },
  '4816': { category: 'Computer Network/Info Services', description: 'Utilities', suggestedBudgetCategory: 'Subscriptions' },
  '4821': { category: 'Telegraph Services', description: 'Utilities', suggestedBudgetCategory: 'Utilities' },
  '4829': { category: 'Wire Transfers/Money Orders', description: 'Financial', suggestedBudgetCategory: 'Financial Services' },
  '4899': { category: 'Cable/Satellite/Pay TV/Radio', description: 'Utilities', suggestedBudgetCategory: 'Subscriptions' },
  '4900': { category: 'Utilities – Electric, Gas, Water, Sanitary', description: 'Utilities', suggestedBudgetCategory: 'Utilities' },

  // ─── Retail / Shopping ───────────────────────────────────────────────
  '5013': { category: 'Motor Vehicle Supplies/Parts', description: 'Auto', suggestedBudgetCategory: 'Auto & Gas' },
  '5021': { category: 'Office/Commercial Furniture', description: 'Shopping', suggestedBudgetCategory: 'Shopping' },
  '5039': { category: 'Construction Materials', description: 'Home', suggestedBudgetCategory: 'Home Improvement' },
  '5044': { category: 'Photographic/Copy/Microfilm Equipment', description: 'Shopping', suggestedBudgetCategory: 'Shopping' },
  '5045': { category: 'Computers/Peripherals/Software', description: 'Electronics', suggestedBudgetCategory: 'Electronics' },
  '5046': { category: 'Commercial Equipment', description: 'Shopping', suggestedBudgetCategory: 'Shopping' },
  '5047': { category: 'Medical/Dental/Lab Equipment', description: 'Healthcare', suggestedBudgetCategory: 'Healthcare' },
  '5051': { category: 'Metal Service Centers', description: 'Shopping', suggestedBudgetCategory: 'Shopping' },
  '5065': { category: 'Electrical Parts/Equipment', description: 'Shopping', suggestedBudgetCategory: 'Shopping' },
  '5072': { category: 'Hardware Equipment/Supplies', description: 'Home', suggestedBudgetCategory: 'Home Improvement' },
  '5074': { category: 'Plumbing/Heating Equipment', description: 'Home', suggestedBudgetCategory: 'Home Improvement' },
  '5085': { category: 'Industrial Supplies', description: 'Shopping', suggestedBudgetCategory: 'Shopping' },
  '5094': { category: 'Precious Stones/Metals/Watches/Jewelry', description: 'Shopping', suggestedBudgetCategory: 'Shopping' },
  '5099': { category: 'Durable Goods (Not Classified)', description: 'Shopping', suggestedBudgetCategory: 'Shopping' },
  '5111': { category: 'Stationery/Office Supplies', description: 'Shopping', suggestedBudgetCategory: 'Shopping' },
  '5122': { category: 'Drugs/Drug Proprietaries/Sundries', description: 'Healthcare', suggestedBudgetCategory: 'Healthcare' },
  '5131': { category: 'Piece Goods/Notions/Dry Goods', description: 'Shopping', suggestedBudgetCategory: 'Shopping' },
  '5137': { category: 'Uniforms/Commercial Clothing', description: 'Clothing', suggestedBudgetCategory: 'Clothing' },
  '5139': { category: 'Commercial Footwear', description: 'Clothing', suggestedBudgetCategory: 'Clothing' },
  '5169': { category: 'Chemicals/Allied Products', description: 'Shopping', suggestedBudgetCategory: 'Shopping' },
  '5172': { category: 'Petroleum/Petroleum Products', description: 'Auto', suggestedBudgetCategory: 'Auto & Gas' },
  '5192': { category: 'Books/Periodicals/Newspapers', description: 'Shopping', suggestedBudgetCategory: 'Shopping' },
  '5193': { category: 'Florists Supplies/Nursery Stock', description: 'Shopping', suggestedBudgetCategory: 'Shopping' },
  '5198': { category: 'Paints/Varnishes/Supplies', description: 'Home', suggestedBudgetCategory: 'Home Improvement' },
  '5199': { category: 'Nondurable Goods', description: 'Shopping', suggestedBudgetCategory: 'Shopping' },
  '5200': { category: 'Home Supply Warehouse Stores', description: 'Home', suggestedBudgetCategory: 'Home Improvement' },
  '5211': { category: 'Lumber/Building Materials', description: 'Home', suggestedBudgetCategory: 'Home Improvement' },
  '5231': { category: 'Glass/Paint/Wallpaper Stores', description: 'Home', suggestedBudgetCategory: 'Home Improvement' },
  '5251': { category: 'Hardware Stores', description: 'Home', suggestedBudgetCategory: 'Home Improvement' },
  '5261': { category: 'Nurseries/Lawn & Garden Supply', description: 'Home', suggestedBudgetCategory: 'Home Improvement' },
  '5271': { category: 'Mobile Home Dealers', description: 'Home', suggestedBudgetCategory: 'Home Improvement' },
  '5300': { category: 'Wholesale Clubs', description: 'Shopping', suggestedBudgetCategory: 'Groceries' },
  '5309': { category: 'Duty Free Stores', description: 'Shopping', suggestedBudgetCategory: 'Shopping' },
  '5310': { category: 'Discount Stores', description: 'Shopping', suggestedBudgetCategory: 'Shopping' },
  '5311': { category: 'Department Stores', description: 'Shopping', suggestedBudgetCategory: 'Shopping' },
  '5331': { category: 'Variety Stores', description: 'Shopping', suggestedBudgetCategory: 'Shopping' },
  '5399': { category: 'Misc General Merchandise', description: 'Shopping', suggestedBudgetCategory: 'Shopping' },

  // ─── Grocery / Food ──────────────────────────────────────────────────
  '5411': { category: 'Grocery Stores, Supermarkets', description: 'Grocery', suggestedBudgetCategory: 'Groceries' },
  '5412': { category: 'Freezer/Locker Meat Provisioners', description: 'Grocery', suggestedBudgetCategory: 'Groceries' },
  '5422': { category: 'Freezer/Locker Meat Provisioners', description: 'Grocery', suggestedBudgetCategory: 'Groceries' },
  '5441': { category: 'Candy/Nut/Confection Stores', description: 'Grocery', suggestedBudgetCategory: 'Groceries' },
  '5451': { category: 'Dairy Product Stores', description: 'Grocery', suggestedBudgetCategory: 'Groceries' },
  '5462': { category: 'Bakeries', description: 'Grocery', suggestedBudgetCategory: 'Groceries' },
  '5499': { category: 'Misc Food Stores – Convenience/Specialty', description: 'Grocery', suggestedBudgetCategory: 'Groceries' },

  // ─── Auto / Gas ──────────────────────────────────────────────────────
  '5511': { category: 'Car/Truck Dealers (New/Used)', description: 'Auto', suggestedBudgetCategory: 'Auto & Gas' },
  '5521': { category: 'Car/Truck Dealers (Used)', description: 'Auto', suggestedBudgetCategory: 'Auto & Gas' },
  '5531': { category: 'Auto/Home Supply Stores', description: 'Auto', suggestedBudgetCategory: 'Auto & Gas' },
  '5532': { category: 'Automotive Tire Stores', description: 'Auto', suggestedBudgetCategory: 'Auto & Gas' },
  '5533': { category: 'Automotive Parts/Accessories', description: 'Auto', suggestedBudgetCategory: 'Auto & Gas' },
  '5541': { category: 'Service Stations (with/without Ancillary)', description: 'Gas', suggestedBudgetCategory: 'Auto & Gas' },
  '5542': { category: 'Automated Fuel Dispensers', description: 'Gas', suggestedBudgetCategory: 'Auto & Gas' },
  '5551': { category: 'Boat Dealers', description: 'Shopping', suggestedBudgetCategory: 'Shopping' },
  '5561': { category: 'Camper/RV/Utility Trailer Dealers', description: 'Shopping', suggestedBudgetCategory: 'Shopping' },
  '5571': { category: 'Motorcycle Shops/Dealers', description: 'Auto', suggestedBudgetCategory: 'Auto & Gas' },
  '5592': { category: 'Motor Home Dealers', description: 'Shopping', suggestedBudgetCategory: 'Shopping' },
  '5598': { category: 'Snowmobile Dealers', description: 'Shopping', suggestedBudgetCategory: 'Shopping' },
  '5599': { category: 'Misc Auto Dealers', description: 'Auto', suggestedBudgetCategory: 'Auto & Gas' },

  // ─── Clothing / Apparel ──────────────────────────────────────────────
  '5611': { category: "Men's/Boy's Clothing/Accessories", description: 'Clothing', suggestedBudgetCategory: 'Clothing' },
  '5621': { category: "Women's Ready-To-Wear", description: 'Clothing', suggestedBudgetCategory: 'Clothing' },
  '5631': { category: "Women's Accessories/Specialty", description: 'Clothing', suggestedBudgetCategory: 'Clothing' },
  '5641': { category: "Children's/Infant's Wear", description: 'Clothing', suggestedBudgetCategory: 'Clothing' },
  '5651': { category: 'Family Clothing Stores', description: 'Clothing', suggestedBudgetCategory: 'Clothing' },
  '5655': { category: 'Sports/Riding Apparel', description: 'Clothing', suggestedBudgetCategory: 'Clothing' },
  '5661': { category: 'Shoe Stores', description: 'Clothing', suggestedBudgetCategory: 'Clothing' },
  '5681': { category: 'Furriers/Fur Shops', description: 'Clothing', suggestedBudgetCategory: 'Clothing' },
  '5691': { category: "Men's/Women's Clothing", description: 'Clothing', suggestedBudgetCategory: 'Clothing' },
  '5697': { category: 'Tailors/Seamstresses/Alterations', description: 'Clothing', suggestedBudgetCategory: 'Clothing' },
  '5698': { category: 'Wig/Toupee Stores', description: 'Personal Care', suggestedBudgetCategory: 'Personal Care' },
  '5699': { category: 'Misc Apparel/Accessory Shops', description: 'Clothing', suggestedBudgetCategory: 'Clothing' },

  // ─── Home Furnishings ────────────────────────────────────────────────
  '5712': { category: 'Furniture/Home Furnishings/Equipment Stores', description: 'Home', suggestedBudgetCategory: 'Home Improvement' },
  '5713': { category: 'Floor Covering Stores', description: 'Home', suggestedBudgetCategory: 'Home Improvement' },
  '5714': { category: 'Drapery/Window Covering/Upholstery', description: 'Home', suggestedBudgetCategory: 'Home Improvement' },
  '5718': { category: 'Fireplace/Fireplace Screens/Accessories', description: 'Home', suggestedBudgetCategory: 'Home Improvement' },
  '5719': { category: 'Misc Home Furnishing Specialty Stores', description: 'Home', suggestedBudgetCategory: 'Home Improvement' },
  '5722': { category: 'Household Appliance Stores', description: 'Home', suggestedBudgetCategory: 'Home Improvement' },

  // ─── Electronics ─────────────────────────────────────────────────────
  '5732': { category: 'Electronics Stores', description: 'Electronics', suggestedBudgetCategory: 'Electronics' },
  '5733': { category: 'Music Stores/Musical Instruments/Pianos', description: 'Entertainment', suggestedBudgetCategory: 'Entertainment' },
  '5734': { category: 'Computer Software Stores', description: 'Electronics', suggestedBudgetCategory: 'Electronics' },
  '5735': { category: 'Record Stores', description: 'Entertainment', suggestedBudgetCategory: 'Entertainment' },

  // ─── Specialty Retail ────────────────────────────────────────────────
  '5811': { category: 'Caterers', description: 'Dining', suggestedBudgetCategory: 'Eating Out' },
  '5812': { category: 'Eating Places, Restaurants', description: 'Dining', suggestedBudgetCategory: 'Eating Out' },
  '5813': { category: 'Drinking Places (Bars, Taverns)', description: 'Dining', suggestedBudgetCategory: 'Eating Out' },
  '5814': { category: 'Fast Food Restaurants', description: 'Dining', suggestedBudgetCategory: 'Eating Out' },
  '5815': { category: 'Digital Goods: Media/Books/Movies/Music', description: 'Digital', suggestedBudgetCategory: 'Subscriptions' },
  '5816': { category: 'Digital Goods: Games', description: 'Digital', suggestedBudgetCategory: 'Entertainment' },
  '5817': { category: 'Digital Goods: Applications', description: 'Digital', suggestedBudgetCategory: 'Subscriptions' },
  '5818': { category: 'Digital Goods: Large Digital Goods Merchant', description: 'Digital', suggestedBudgetCategory: 'Subscriptions' },
  '5912': { category: 'Drug Stores/Pharmacies', description: 'Healthcare', suggestedBudgetCategory: 'Healthcare' },
  '5921': { category: 'Package Stores – Beer/Wine/Liquor', description: 'Grocery', suggestedBudgetCategory: 'Groceries' },
  '5931': { category: 'Used Merchandise/Secondhand Stores', description: 'Shopping', suggestedBudgetCategory: 'Shopping' },
  '5932': { category: 'Antique Shops', description: 'Shopping', suggestedBudgetCategory: 'Shopping' },
  '5933': { category: 'Pawn Shops', description: 'Shopping', suggestedBudgetCategory: 'Shopping' },
  '5935': { category: 'Wrecking/Salvage Yards', description: 'Auto', suggestedBudgetCategory: 'Auto & Gas' },
  '5937': { category: 'Antique Reproductions', description: 'Shopping', suggestedBudgetCategory: 'Shopping' },
  '5940': { category: 'Bicycle Shops', description: 'Shopping', suggestedBudgetCategory: 'Shopping' },
  '5941': { category: 'Sporting Goods Stores', description: 'Sports', suggestedBudgetCategory: 'Fitness & Sports' },
  '5942': { category: 'Book Stores', description: 'Shopping', suggestedBudgetCategory: 'Shopping' },
  '5943': { category: 'Stationery/Office/School Supplies', description: 'Shopping', suggestedBudgetCategory: 'Shopping' },
  '5944': { category: 'Jewelry Stores/Watches/Clocks/Silverware', description: 'Shopping', suggestedBudgetCategory: 'Shopping' },
  '5945': { category: 'Hobby/Toy/Game Shops', description: 'Shopping', suggestedBudgetCategory: 'Shopping' },
  '5946': { category: 'Camera/Photographic Supply Stores', description: 'Shopping', suggestedBudgetCategory: 'Shopping' },
  '5947': { category: 'Gift/Card/Novelty/Souvenir Shops', description: 'Shopping', suggestedBudgetCategory: 'Shopping' },
  '5948': { category: 'Luggage/Leather Goods Stores', description: 'Shopping', suggestedBudgetCategory: 'Shopping' },
  '5949': { category: 'Sewing/Needlework/Fabric/Piece Goods', description: 'Shopping', suggestedBudgetCategory: 'Shopping' },
  '5950': { category: 'Glassware/Crystal Stores', description: 'Shopping', suggestedBudgetCategory: 'Shopping' },
  '5960': { category: 'Direct Marketing – Insurance Services', description: 'Insurance', suggestedBudgetCategory: 'Insurance' },
  '5961': { category: 'Mail Order Houses/Catalog', description: 'Shopping', suggestedBudgetCategory: 'Shopping' },
  '5962': { category: 'Telemarketing/Direct Marketing', description: 'Shopping', suggestedBudgetCategory: 'Shopping' },
  '5963': { category: 'Door-To-Door Sales', description: 'Shopping', suggestedBudgetCategory: 'Shopping' },
  '5964': { category: 'Direct Marketing – Catalog Merchant', description: 'Shopping', suggestedBudgetCategory: 'Shopping' },
  '5965': { category: 'Direct Marketing – Combination Catalog/Retail', description: 'Shopping', suggestedBudgetCategory: 'Shopping' },
  '5966': { category: 'Direct Marketing – Outbound Telemarketing', description: 'Shopping', suggestedBudgetCategory: 'Shopping' },
  '5967': { category: 'Direct Marketing – Inbound Teleservices', description: 'Shopping', suggestedBudgetCategory: 'Shopping' },
  '5968': { category: 'Direct Marketing – Subscription', description: 'Subscriptions', suggestedBudgetCategory: 'Subscriptions' },
  '5969': { category: 'Direct Marketing – Other', description: 'Shopping', suggestedBudgetCategory: 'Shopping' },
  '5970': { category: "Artist's Supply/Craft Stores", description: 'Shopping', suggestedBudgetCategory: 'Shopping' },
  '5971': { category: 'Art Dealers/Galleries', description: 'Shopping', suggestedBudgetCategory: 'Shopping' },
  '5972': { category: 'Stamp/Coin Stores', description: 'Shopping', suggestedBudgetCategory: 'Shopping' },
  '5973': { category: 'Religious Goods Stores', description: 'Shopping', suggestedBudgetCategory: 'Shopping' },
  '5975': { category: 'Hearing Aids', description: 'Healthcare', suggestedBudgetCategory: 'Healthcare' },
  '5976': { category: 'Orthopedic Goods/Prosthetic Devices', description: 'Healthcare', suggestedBudgetCategory: 'Healthcare' },
  '5977': { category: 'Cosmetic Stores', description: 'Personal Care', suggestedBudgetCategory: 'Personal Care' },
  '5978': { category: 'Typewriter Stores', description: 'Shopping', suggestedBudgetCategory: 'Shopping' },
  '5983': { category: 'Fuel Dealers – Non-Automotive', description: 'Utilities', suggestedBudgetCategory: 'Utilities' },
  '5992': { category: 'Florists', description: 'Shopping', suggestedBudgetCategory: 'Shopping' },
  '5993': { category: 'Cigar Stores/Stands', description: 'Shopping', suggestedBudgetCategory: 'Shopping' },
  '5994': { category: 'News Dealers/Newsstands', description: 'Shopping', suggestedBudgetCategory: 'Shopping' },
  '5995': { category: 'Pet Shops/Pet Food/Supplies', description: 'Pet', suggestedBudgetCategory: 'Pet' },
  '5996': { category: 'Swimming Pools – Sales/Service/Supplies', description: 'Home', suggestedBudgetCategory: 'Home Improvement' },
  '5997': { category: 'Electric Razor Stores', description: 'Personal Care', suggestedBudgetCategory: 'Personal Care' },
  '5998': { category: 'Tent/Awning Shops', description: 'Shopping', suggestedBudgetCategory: 'Shopping' },
  '5999': { category: 'Miscellaneous/Specialty Retail', description: 'Shopping', suggestedBudgetCategory: 'Shopping' },

  // ─── Services ────────────────────────────────────────────────────────
  '6010': { category: 'Financial Institutions – Manual Cash Disbursements', description: 'Financial', suggestedBudgetCategory: 'Financial Services' },
  '6011': { category: 'Financial Institutions – Automated Cash Disbursements', description: 'Financial', suggestedBudgetCategory: 'Financial Services' },
  '6012': { category: 'Financial Institutions – Merchandise/Services', description: 'Financial', suggestedBudgetCategory: 'Financial Services' },
  '6051': { category: 'Non-Financial Institutions – Foreign Currency/Money Orders', description: 'Financial', suggestedBudgetCategory: 'Financial Services' },
  '6211': { category: 'Security Brokers/Dealers', description: 'Financial', suggestedBudgetCategory: 'Financial Services' },
  '6300': { category: 'Insurance Underwriting/Premiums', description: 'Insurance', suggestedBudgetCategory: 'Insurance' },
  '6381': { category: 'Insurance Premiums', description: 'Insurance', suggestedBudgetCategory: 'Insurance' },
  '6399': { category: 'Insurance – Not Classified', description: 'Insurance', suggestedBudgetCategory: 'Insurance' },
  '6513': { category: 'Real Estate Agents/Managers – Rentals', description: 'Housing', suggestedBudgetCategory: 'Rent & Mortgage' },
  '6540': { category: 'Non-Financial Institutions – Stored Value Card Purchase/Load', description: 'Financial', suggestedBudgetCategory: 'Financial Services' },

  // ─── Professional Services ───────────────────────────────────────────
  '7011': { category: 'Hotels, Motels, Resorts', description: 'Lodging', suggestedBudgetCategory: 'Travel' },
  '7012': { category: 'Timeshares', description: 'Travel', suggestedBudgetCategory: 'Travel' },
  '7032': { category: 'Sporting/Recreation Camps', description: 'Entertainment', suggestedBudgetCategory: 'Entertainment' },
  '7033': { category: 'Trailer Parks/Campgrounds', description: 'Travel', suggestedBudgetCategory: 'Travel' },
  '7210': { category: 'Laundry/Cleaning/Garment Services', description: 'Personal Care', suggestedBudgetCategory: 'Personal Care' },
  '7211': { category: 'Laundry Services – Family/Commercial', description: 'Personal Care', suggestedBudgetCategory: 'Personal Care' },
  '7216': { category: 'Dry Cleaners', description: 'Personal Care', suggestedBudgetCategory: 'Personal Care' },
  '7217': { category: 'Carpet/Upholstery Cleaning', description: 'Home', suggestedBudgetCategory: 'Home Improvement' },
  '7221': { category: 'Photographic Studios', description: 'Shopping', suggestedBudgetCategory: 'Shopping' },
  '7230': { category: 'Beauty/Barber Shops', description: 'Personal Care', suggestedBudgetCategory: 'Personal Care' },
  '7251': { category: 'Shoe Repair/Hat Cleaning', description: 'Shopping', suggestedBudgetCategory: 'Shopping' },
  '7261': { category: 'Funeral Services/Crematories', description: 'Services', suggestedBudgetCategory: 'Shopping' },
  '7273': { category: 'Dating/Escort Services', description: 'Entertainment', suggestedBudgetCategory: 'Entertainment' },
  '7276': { category: 'Tax Preparation Services', description: 'Financial', suggestedBudgetCategory: 'Financial Services' },
  '7277': { category: 'Counseling Services', description: 'Healthcare', suggestedBudgetCategory: 'Healthcare' },
  '7278': { category: 'Buying/Shopping Services', description: 'Shopping', suggestedBudgetCategory: 'Shopping' },
  '7296': { category: 'Clothing Rental', description: 'Clothing', suggestedBudgetCategory: 'Clothing' },
  '7297': { category: 'Massage Parlors', description: 'Personal Care', suggestedBudgetCategory: 'Personal Care' },
  '7298': { category: 'Health/Beauty Spas', description: 'Personal Care', suggestedBudgetCategory: 'Personal Care' },
  '7299': { category: 'Misc Recreation Services', description: 'Entertainment', suggestedBudgetCategory: 'Entertainment' },
  '7311': { category: 'Advertising Services', description: 'Services', suggestedBudgetCategory: 'Shopping' },
  '7321': { category: 'Consumer Credit Reporting Agencies', description: 'Financial', suggestedBudgetCategory: 'Financial Services' },
  '7333': { category: 'Commercial Photography/Art/Graphics', description: 'Services', suggestedBudgetCategory: 'Shopping' },
  '7338': { category: 'Quick Copy/Repro/Blueprinting', description: 'Services', suggestedBudgetCategory: 'Shopping' },
  '7339': { category: 'Stenographic/Secretarial Support', description: 'Services', suggestedBudgetCategory: 'Shopping' },
  '7342': { category: 'Exterminating/Disinfecting Services', description: 'Home', suggestedBudgetCategory: 'Home Improvement' },
  '7349': { category: 'Cleaning/Maintenance/Janitorial', description: 'Home', suggestedBudgetCategory: 'Home Improvement' },
  '7361': { category: 'Employment/Temp Agencies', description: 'Services', suggestedBudgetCategory: 'Shopping' },
  '7372': { category: 'Computer Programming/Data Processing', description: 'Services', suggestedBudgetCategory: 'Subscriptions' },
  '7375': { category: 'Information Retrieval Services', description: 'Services', suggestedBudgetCategory: 'Subscriptions' },
  '7379': { category: 'Computer Repair', description: 'Electronics', suggestedBudgetCategory: 'Electronics' },
  '7392': { category: 'Consulting/Public Relations', description: 'Services', suggestedBudgetCategory: 'Shopping' },
  '7393': { category: 'Detective/Protective Agencies/Security', description: 'Services', suggestedBudgetCategory: 'Shopping' },
  '7394': { category: 'Equipment Rental/Leasing', description: 'Services', suggestedBudgetCategory: 'Shopping' },
  '7395': { category: 'Photo Developing', description: 'Services', suggestedBudgetCategory: 'Shopping' },
  '7399': { category: 'Misc Business Services', description: 'Services', suggestedBudgetCategory: 'Shopping' },

  // ─── Auto Services ───────────────────────────────────────────────────
  '7511': { category: 'Truck Stop', description: 'Auto', suggestedBudgetCategory: 'Auto & Gas' },
  '7512': { category: 'Car Rental Agencies', description: 'Travel', suggestedBudgetCategory: 'Travel' },
  '7513': { category: 'Truck/Utility Trailer Rentals', description: 'Shopping', suggestedBudgetCategory: 'Shopping' },
  '7519': { category: 'Motor Home/RV Rentals', description: 'Travel', suggestedBudgetCategory: 'Travel' },
  '7523': { category: 'Parking Lots/Garages', description: 'Transportation', suggestedBudgetCategory: 'Transportation' },
  '7531': { category: 'Auto Body Repair Shops', description: 'Auto', suggestedBudgetCategory: 'Auto & Gas' },
  '7534': { category: 'Tire Re-treading/Repair', description: 'Auto', suggestedBudgetCategory: 'Auto & Gas' },
  '7535': { category: 'Auto Paint Shops', description: 'Auto', suggestedBudgetCategory: 'Auto & Gas' },
  '7538': { category: 'Auto Service Shops (Non-Dealer)', description: 'Auto', suggestedBudgetCategory: 'Auto & Gas' },
  '7542': { category: 'Car Washes', description: 'Auto', suggestedBudgetCategory: 'Auto & Gas' },
  '7549': { category: 'Towing Services', description: 'Auto', suggestedBudgetCategory: 'Auto & Gas' },

  // ─── Entertainment / Recreation ──────────────────────────────────────
  '7622': { category: 'Electronics Repair Shops', description: 'Electronics', suggestedBudgetCategory: 'Electronics' },
  '7623': { category: 'A/C, Refrigeration Repair', description: 'Home', suggestedBudgetCategory: 'Home Improvement' },
  '7629': { category: 'Appliance Repair Shops', description: 'Home', suggestedBudgetCategory: 'Home Improvement' },
  '7631': { category: 'Watch/Clock/Jewelry Repair', description: 'Shopping', suggestedBudgetCategory: 'Shopping' },
  '7641': { category: 'Furniture Reupholstery/Repair', description: 'Home', suggestedBudgetCategory: 'Home Improvement' },
  '7692': { category: 'Welding Repair', description: 'Services', suggestedBudgetCategory: 'Shopping' },
  '7699': { category: 'Misc Repair Shops/Related Services', description: 'Services', suggestedBudgetCategory: 'Shopping' },
  '7800': { category: 'Government-Owned Lotteries', description: 'Entertainment', suggestedBudgetCategory: 'Entertainment' },
  '7801': { category: 'Government-Licensed Online Casinos', description: 'Entertainment', suggestedBudgetCategory: 'Entertainment' },
  '7802': { category: 'Government-Licensed Horse/Dog Racing', description: 'Entertainment', suggestedBudgetCategory: 'Entertainment' },
  '7829': { category: 'Motion Picture/Video Tape Production/Distribution', description: 'Entertainment', suggestedBudgetCategory: 'Entertainment' },
  '7832': { category: 'Motion Picture Theaters', description: 'Entertainment', suggestedBudgetCategory: 'Entertainment' },
  '7841': { category: 'Video Tape Rental Stores', description: 'Entertainment', suggestedBudgetCategory: 'Entertainment' },
  '7911': { category: 'Dance Halls/Studios/Schools', description: 'Entertainment', suggestedBudgetCategory: 'Entertainment' },
  '7922': { category: 'Theatrical Ticket Agencies', description: 'Entertainment', suggestedBudgetCategory: 'Entertainment' },
  '7929': { category: 'Bands/Orchestras/Entertainers', description: 'Entertainment', suggestedBudgetCategory: 'Entertainment' },
  '7932': { category: 'Billiard/Pool Establishments', description: 'Entertainment', suggestedBudgetCategory: 'Entertainment' },
  '7933': { category: 'Bowling Alleys', description: 'Entertainment', suggestedBudgetCategory: 'Entertainment' },
  '7941': { category: 'Commercial Sports/Athletic Fields/Clubs/Promoters', description: 'Entertainment', suggestedBudgetCategory: 'Entertainment' },
  '7991': { category: 'Tourist Attractions/Exhibits', description: 'Entertainment', suggestedBudgetCategory: 'Entertainment' },
  '7992': { category: 'Golf Courses – Public', description: 'Entertainment', suggestedBudgetCategory: 'Fitness & Sports' },
  '7993': { category: 'Video Amusement Game Supplies', description: 'Entertainment', suggestedBudgetCategory: 'Entertainment' },
  '7994': { category: 'Video Game Arcades/Establishments', description: 'Entertainment', suggestedBudgetCategory: 'Entertainment' },
  '7995': { category: 'Betting/Casino Gambling', description: 'Entertainment', suggestedBudgetCategory: 'Entertainment' },
  '7996': { category: 'Amusement Parks/Circuses/Carnivals', description: 'Entertainment', suggestedBudgetCategory: 'Entertainment' },
  '7997': { category: 'Clubs – Country/Membership (Athletic/Recreation/Sports)', description: 'Fitness', suggestedBudgetCategory: 'Fitness & Sports' },
  '7998': { category: 'Aquariums/Seaquariums/Dolphinariums', description: 'Entertainment', suggestedBudgetCategory: 'Entertainment' },
  '7999': { category: 'Recreation Services (Not Classified)', description: 'Entertainment', suggestedBudgetCategory: 'Entertainment' },

  // ─── Healthcare ──────────────────────────────────────────────────────
  '8011': { category: 'Doctors (Not Classified)', description: 'Healthcare', suggestedBudgetCategory: 'Healthcare' },
  '8021': { category: 'Dentists/Orthodontists', description: 'Healthcare', suggestedBudgetCategory: 'Healthcare' },
  '8031': { category: 'Osteopathic Physicians', description: 'Healthcare', suggestedBudgetCategory: 'Healthcare' },
  '8041': { category: 'Chiropractors', description: 'Healthcare', suggestedBudgetCategory: 'Healthcare' },
  '8042': { category: 'Optometrists/Ophthalmologists', description: 'Healthcare', suggestedBudgetCategory: 'Healthcare' },
  '8043': { category: 'Opticians/Optical Goods/Eyeglasses', description: 'Healthcare', suggestedBudgetCategory: 'Healthcare' },
  '8044': { category: 'Opticians/Optical Goods/Eyeglasses', description: 'Healthcare', suggestedBudgetCategory: 'Healthcare' },
  '8049': { category: 'Podiatrists/Chiropodists', description: 'Healthcare', suggestedBudgetCategory: 'Healthcare' },
  '8050': { category: 'Nursing/Personal Care Facilities', description: 'Healthcare', suggestedBudgetCategory: 'Healthcare' },
  '8062': { category: 'Hospitals', description: 'Healthcare', suggestedBudgetCategory: 'Healthcare' },
  '8071': { category: 'Medical/Dental Labs', description: 'Healthcare', suggestedBudgetCategory: 'Healthcare' },
  '8099': { category: 'Medical Services/Health Practitioners', description: 'Healthcare', suggestedBudgetCategory: 'Healthcare' },

  // ─── Professional Services ───────────────────────────────────────────
  '8111': { category: 'Legal Services/Attorneys', description: 'Professional', suggestedBudgetCategory: 'Professional Services' },
  '8211': { category: 'Elementary/Secondary Schools', description: 'Education', suggestedBudgetCategory: 'Education' },
  '8220': { category: 'Colleges/Universities/Professional Schools', description: 'Education', suggestedBudgetCategory: 'Education' },
  '8241': { category: 'Correspondence Schools', description: 'Education', suggestedBudgetCategory: 'Education' },
  '8244': { category: 'Business/Secretarial Schools', description: 'Education', suggestedBudgetCategory: 'Education' },
  '8249': { category: 'Vocational/Trade Schools', description: 'Education', suggestedBudgetCategory: 'Education' },
  '8299': { category: 'Educational Services (Not Classified)', description: 'Education', suggestedBudgetCategory: 'Education' },
  '8351': { category: 'Child Care Services', description: 'Childcare', suggestedBudgetCategory: 'Childcare' },
  '8398': { category: 'Charitable/Social Service Organizations', description: 'Charity', suggestedBudgetCategory: 'Charity' },
  '8641': { category: 'Civic/Social/Fraternal Associations', description: 'Charity', suggestedBudgetCategory: 'Charity' },
  '8651': { category: 'Political Organizations', description: 'Charity', suggestedBudgetCategory: 'Charity' },
  '8661': { category: 'Religious Organizations', description: 'Charity', suggestedBudgetCategory: 'Charity' },
  '8675': { category: 'Automobile Associations', description: 'Auto', suggestedBudgetCategory: 'Auto & Gas' },
  '8699': { category: 'Membership Organizations', description: 'Subscriptions', suggestedBudgetCategory: 'Subscriptions' },
  '8734': { category: 'Testing Laboratories', description: 'Services', suggestedBudgetCategory: 'Shopping' },
  '8911': { category: 'Architectural/Engineering/Surveying', description: 'Professional', suggestedBudgetCategory: 'Professional Services' },
  '8931': { category: 'Accounting/Auditing/Bookkeeping', description: 'Professional', suggestedBudgetCategory: 'Professional Services' },
  '8999': { category: 'Professional Services (Not Classified)', description: 'Professional', suggestedBudgetCategory: 'Professional Services' },

  // ─── Government ──────────────────────────────────────────────────────
  '9211': { category: 'Court Costs/Alimony/Child Support', description: 'Government', suggestedBudgetCategory: 'Government & Tax' },
  '9222': { category: 'Fines', description: 'Government', suggestedBudgetCategory: 'Government & Tax' },
  '9223': { category: 'Bail/Bond Payments', description: 'Government', suggestedBudgetCategory: 'Government & Tax' },
  '9311': { category: 'Tax Payments', description: 'Government', suggestedBudgetCategory: 'Government & Tax' },
  '9399': { category: 'Government Services', description: 'Government', suggestedBudgetCategory: 'Government & Tax' },
  '9402': { category: 'Postal Services – Government Only', description: 'Government', suggestedBudgetCategory: 'Shopping' },
  '9405': { category: 'Intra-Government Purchases', description: 'Government', suggestedBudgetCategory: 'Government & Tax' },
  '9700': { category: 'Automated Referral Service', description: 'Services', suggestedBudgetCategory: 'Shopping' },
  '9950': { category: 'Intra-Company Purchases', description: 'Financial', suggestedBudgetCategory: 'Financial Services' },

  // ─── Fitness / Gym ───────────────────────────────────────────────────
  '7941': { category: 'Sports Clubs/Fields/Promoters', description: 'Fitness', suggestedBudgetCategory: 'Fitness & Sports' },
  '7997': { category: 'Country Clubs/Membership (Athletic)', description: 'Fitness', suggestedBudgetCategory: 'Fitness & Sports' },
  '7298': { category: 'Health/Beauty Spas', description: 'Fitness', suggestedBudgetCategory: 'Personal Care' },
};

/**
 * Look up an MCC code and return its entry, or null if not found.
 */
export function lookupMCC(code: string): MCCEntry | null {
  return MCC_CODES[code] ?? null;
}

/**
 * Get all unique budget categories from MCC codes.
 */
export function getAllBudgetCategories(): string[] {
  const categories = new Set<string>();
  for (const entry of Object.values(MCC_CODES)) {
    categories.add(entry.suggestedBudgetCategory);
  }
  return Array.from(categories).sort();
}
